// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlT7Wj6zg_2W3WmWO8RFVVgFzwJXVT5i4',
    appId: '1:741697378258:web:ebe8911f4cb6d14bd51a0b',
    messagingSenderId: '741697378258',
    projectId: 'todoapp-18531',
    authDomain: 'todoapp-18531.firebaseapp.com',
    storageBucket: 'todoapp-18531.appspot.com',
    measurementId: 'G-GBQSQNQ8GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfJXjydIMFbqGKd8SdvvxsiHlfgA2w8zo',
    appId: '1:741697378258:android:536d72a57425382ed51a0b',
    messagingSenderId: '741697378258',
    projectId: 'todoapp-18531',
    storageBucket: 'todoapp-18531.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMkTxxemoVQrLtAs0WLKsDJGV8ZrY-A9c',
    appId: '1:741697378258:ios:c6edf5347148520ed51a0b',
    messagingSenderId: '741697378258',
    projectId: 'todoapp-18531',
    storageBucket: 'todoapp-18531.appspot.com',
    iosClientId: '741697378258-qqmfpmh7okf5v2iqo17tl6o6h4mft5f4.apps.googleusercontent.com',
    iosBundleId: 'in.todo.app.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMkTxxemoVQrLtAs0WLKsDJGV8ZrY-A9c',
    appId: '1:741697378258:ios:c6edf5347148520ed51a0b',
    messagingSenderId: '741697378258',
    projectId: 'todoapp-18531',
    storageBucket: 'todoapp-18531.appspot.com',
    iosClientId: '741697378258-qqmfpmh7okf5v2iqo17tl6o6h4mft5f4.apps.googleusercontent.com',
    iosBundleId: 'in.todo.app.todoapp',
  );
}
